services:
  - type: web
    name: memecoin-telegram-bot
    runtime: python
    plan: free
    buildCommand: pip install -r requirements.txt
    startCommand: python3 main.py
    envVars:
      - key: TELEGRAM_BOT_TOKEN
        sync: false
      - key: HF_API_TOKEN
        sync: false
      - key: WALLET_1
        sync: false
      - key: WALLET_2
        sync: false
      # Add WALLET_3 through WALLET_10 if needed
