services:
  - type: web
    name: memecoin-telegram-bot
    runtime: python
    buildCommand: pip install -r requirements.txt
    startCommand: python3 main.py
    plan: free
    envVars:
      - key: TELEGRAM_BOT_TOKEN
        sync: false
      - key: HF_API_TOKEN
        sync: false
      - key: WALLET_1
        sync: false
      - key: WALLET_2
        sync: false
      - key: WALLET_3
        sync: false
      - key: WALLET_4
        sync: false
      - key: WALLET_5
        sync: false
      - key: WALLET_6
        sync: false
      - key: WALLET_7
        sync: false
      - key: WALLET_8
        sync: false
      - key: WALLET_9
        sync: false
      - key: WALLET_10
        sync: false
